name: PackageAndDeploy

on:
  push:
    branches: [release/*]

jobs:
  DeploymentDev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - id: step1
      run: echo "Deploiement en dev"
  DeploymentQualif:
    runs-on: ubuntu-latest
    environment: Qualif
    needs: [DeploymentDev]
    steps:
    - id: step1
      run: echo "Deploiement en qualification"
